apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: acedemo-deploy-task
spec:
  resources:
    inputs:
    - name: image
      type: image
  steps:
    - name: oc
      image: quay.io/openshift/origin-cli:latest
      script: |
        cat << EOF | oc apply -f -
        apiVersion: appconnect.ibm.com/v1beta1
        kind: IntegrationServer
        metadata:
          name: ace-demo2
          namespace: ivo-ace-test
        spec:
          pod:
           containers:
             runtime:
               image: $(resources.inputs.image.url)
          configurations: []
          designerFlowsOperationMode: disabled
          license:
            accept: true
            license: L-AMYG-BQ2E4U
            use: CloudPakForIntegrationNonProduction
          replicas: 1
          router:
            timeout: 120s
          service:
            endpointType: http
          useCommonServices: true
          version: 12.0.0
        EOF
